# You can use this file to create a conda environment for the genome-annotation pipeline:
#   conda env create -f environment.yml
name: miRNApipe-1.0
channels:
 - defaults
 - conda-forge
 - bioconda
dependencies:
 - samtools=1.9
 - star=2.7.0e
 - multiqc=1.6
 - fastp=0.19.7
