# You can use this file to create a conda environment for the genome-annotation pipeline:
#   conda env create -f environment.yml
name: mirnaseq-1.0
channels:
 - defaults
 - conda-forge
 - bioconda
dependencies:
 - samtools=1.9
 - star=2.6.1d
 - multiqc=1.7
 - fastp=0.20.0
 - mirtop=0.4.18a
 - seqbuster
 - fastx_toolkit=0.0.14
 - unzip=6.0
 - gzip=1.7
